/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Query
         * @description Execute a Query against DuckDB and return a QueryResult.
         */
        post: operations["run_query_api_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/widgets/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Catalog
         * @description Return the 10 hardcoded starter widget definitions.
         */
        get: operations["get_catalog_api_widgets_catalog_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entities/{lens}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Entities
         * @description Return entity values for a given lens, for use in UI pickers.
         */
        get: operations["get_entities_api_entities__lens__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/findings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Findings
         * @description Paginated finding_state rows. Filters: severity, state. Ordered by last_seen desc.
         */
        get: operations["list_findings_api_findings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workload-counts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Workload Counts
         * @description Return workload counts per CVE aggregated from the latest snapshot date.
         */
        get: operations["get_workload_counts_api_workload_counts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workloads-for-cve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Workloads For Cve
         * @description Return distinct workloads running images that contain the given CVE (OPEN state only).
         */
        get: operations["get_workloads_for_cve_api_workloads_for_cve_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Health check — verifies the DuckDB file exists and is readable.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** FilterIn */
        FilterIn: {
            /** Field */
            field: string;
            /** Operator */
            operator: string;
            /** Value */
            value: unknown;
        };
        /** FindingRow */
        FindingRow: {
            /** Finding Id */
            finding_id: number;
            /** Cve Id */
            cve_id: string;
            /** Severity */
            severity: string;
            /** Image Id */
            image_id: string;
            /** Image Name */
            image_name: string | null;
            /** Package Name */
            package_name: string;
            /** First Seen */
            first_seen: string;
            /** Last Seen */
            last_seen: string;
            /** State */
            state: string;
            /** Reason Code */
            reason_code: string | null;
        };
        /** FindingsResponse */
        FindingsResponse: {
            /** Rows */
            rows: components["schemas"]["FindingRow"][];
            /** Total */
            total: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** OrderingIn */
        OrderingIn: {
            /** Field */
            field: string;
            /**
             * Direction
             * @default asc
             */
            direction: string;
        };
        /** QueryIn */
        QueryIn: {
            /** Lens */
            lens: string;
            /**
             * Traversal
             * @default []
             */
            traversal: string[];
            time: components["schemas"]["TimeWindowIn"];
            /** Measure */
            measure: string;
            /**
             * Filters
             * @default []
             */
            filters: components["schemas"]["FilterIn"][];
            /**
             * Group By
             * @default []
             */
            group_by: string[];
            order_by?: components["schemas"]["OrderingIn"] | null;
            /** Limit */
            limit?: number | null;
        };
        /** QueryResultOut */
        QueryResultOut: {
            /** Series */
            series: components["schemas"]["SeriesOut"][];
            /** Dimensions */
            dimensions: {
                [key: string]: unknown[];
            };
            /** Snapshot Range */
            snapshot_range: string[];
            /** Missing Days */
            missing_days: string[];
            /** Exec Time Ms */
            exec_time_ms: number;
        };
        /** SeriesOut */
        SeriesOut: {
            /** Key */
            key: {
                [key: string]: unknown;
            };
            /** X */
            x: string[];
            /** Y */
            y: (number | null)[];
        };
        /** TimeWindowIn */
        TimeWindowIn: {
            /** Mode */
            mode: string;
            /** N */
            n?: number | null;
            /** Start */
            start?: string | null;
            /** End */
            end?: string | null;
            /**
             * Granularity
             * @default day
             */
            granularity: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WeightedCve */
        WeightedCve: {
            /** Cve Id */
            cve_id: string;
            /** Severity */
            severity: string;
            /** Workload Count */
            workload_count: number;
            /** In Use */
            in_use: boolean;
            /** Fix Available */
            fix_available: boolean;
            /** Public Exploit */
            public_exploit: boolean;
        };
        /** WorkloadCountsResponse */
        WorkloadCountsResponse: {
            /** Counts */
            counts: components["schemas"]["WeightedCve"][];
            /** Snapshot Date */
            snapshot_date: string;
        };
        /** WorkloadRow */
        WorkloadRow: {
            /** Cluster Name */
            cluster_name: string;
            /** Namespace Name */
            namespace_name: string;
            /** Workload Type */
            workload_type: string;
            /** Workload Name */
            workload_name: string;
            /** Container Name */
            container_name: string;
            /** Team Id */
            team_id: string | null;
        };
        /** WorkloadsForCveResponse */
        WorkloadsForCveResponse: {
            /** Cve Id */
            cve_id: string;
            /** Workloads */
            workloads: components["schemas"]["WorkloadRow"][];
            /** Total */
            total: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    run_query_api_query_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryResultOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_catalog_api_widgets_catalog_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    get_entities_api_entities__lens__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lens: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_findings_api_findings_get: {
        parameters: {
            query?: {
                severity?: string | null;
                state?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_workload_counts_api_workload_counts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkloadCountsResponse"];
                };
            };
        };
    };
    get_workloads_for_cve_api_workloads_for_cve_get: {
        parameters: {
            query: {
                /** @description CVE ID to look up */
                cve_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkloadsForCveResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
